version: '3'
services:
  backend:
    image: labs-hr-go-app:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: labs-hr-go
      DB_PASSWORD: labs-hr-go
      DB_DATABASE: labs-hr-go
      DB_SEED: false
      REDIS_ADDR: redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: mysql:9.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: labs-hr-go
      MYSQL_DATABASE: labs-hr-go
      MYSQL_USER: labs-hr-go
      MYSQL_PASSWORD: labs-hr-go
    volumes:
      - './storage/db:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 60s
      retries: 10

  redis:
    image: redis:7.4.3-alpine
    restart: always
    volumes:
      - './storage/redis:/data'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 60s
      retries: 10
