version: '3'
services:
  backend:
    image: labs-hr-go-app:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - './public/downloads:/app/public/downloads'
    environment:
      PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: labs-hr-go
      DB_PASSWORD: labs-hr-go
      DB_DATABASE: labs-hr-go
      WITH_SEED: false
    depends_on:
      - db
      - redis

  db:
    image: mysql:9.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: labs-hr-go
      MYSQL_DATABASE: labs-hr-go
      MYSQL_USER: labs-hr-go
      MYSQL_PASSWORD: labs-hr-go
    volumes:
      - './storage/db:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 60s
      retries: 10

  redis:
    image: redis:7.4.3-alpine
    restart: always
    volumes:
      - './storage/redis:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 60s
      retries: 10
