version: '3'
services:
  db:
    image: mysql:9.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: labs-hr-go
      MYSQL_DATABASE: labs-hr-go
      MYSQL_USER: labs-hr-go
      MYSQL_PASSWORD: labs-hr-go
    volumes:
      - './storage/db:/var/lib/mysql'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 60s
      retries: 10

  redis:
    image: redis:7.4.3-alpine
    restart: always
    volumes:
      - './storage/redis:/data'
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 60s
      retries: 10
